### ISSUE TITLE
ترجمه فصل 4

### ISSUE THREAD

**Issue by mokarramis** [ftg-iran/dfa-persian#18]

**Comment by mthri** [comment]
ممنون از شما
میتونید شروع کنید

**Comment by mthri** [comment]
لطفا یک زمان حدودی از اتمام ترجمه تون اعلام کنید
ممنون

**Comment by mokarramis** [comment]
> لطفا یک زمان حدودی از اتمام ترجمه تون اعلام کنید ممنون

ممنون از شما. سعی میکنم تا آخر بهمن ماه تموم بشه.
