### ISSUE TITLE
Chapter 9

### ISSUE THREAD

**Issue by rezamobaraki** [ftg-iran/dfa-persian#19]
فصل ۹ و در صورت امکان ۶

**Comment by rezamobaraki** [comment]
همچنین اضافه کردن مواردی به ۸

**Comment by mthri** [comment]
سلام
ممنون از شما
میتونید فصل ۹ رو شروع کنید
در مورد فصل ۸ همونطور که داخل گروه گفتم، یک فایل جدا داخل فصل ایجاد کنید و لینک کنید

اگر توی دو سه روز اینده کسی فصل ۶ رو به عهده نگرفت، بهتون اطلاع میدم که شما زحمتش رو بکشید

**Comment by mthri** [comment]
لطفا یک زمان حدودی از اتمام ترجمه تون بفرمایید
