### ISSUE TITLE
با سلام ترجمه فصل ۸ .

### ISSUE THREAD

**Issue by amirpsd** [ftg-iran/dfa-persian#2]
بنده فصل ۸ را ترجمه میکنم با تشکر 🙏

**Comment by mthri** [comment]
ممنون
لطفا شروع کنید

**Comment by mthri** [comment]
لطفا یک زمان حدودی از اتمام ترجمه تون اعلام کنید
ممنون

**Comment by amirpsd** [comment]
با توجه به اینکه امتحانات است ولی سعی میکنم ۳ تا ۴ هفته دیگه تمامش کنم.
