### ISSUE TITLE
chapter 2

### ISSUE THREAD

**Issue by Seyyed-Mahdi-Sepahbodi** [ftg-iran/dfa-persian#22]
(Library Website and API)داوطلب ترجمه فصل دوم

**Comment by mthri** [comment]
سلام
خیلی ممنون، میتونید ترجمه رو شروع کنید
لطفا یک زمان تقریبی از اتمام ترجمه اعلام کنید

**Comment by Seyyed-Mahdi-Sepahbodi** [comment]
سلام با توجه به اینکه تایم امتحانات هست فک میکنم تا نیمه بهمن بتونم تموم کنم
