### ISSUE TITLE
00-Introduction

### ISSUE THREAD

**Issue by MKarimi21** [ftg-iran/dfa-persian#23]
با عرض سلام

با این که تخصص زیادی در جنگو ندارم اما با پایتون و فریم ورک ها و ضمن اینکه کمک به پایتونی ها دارم علاقه مندم برای ترجمه برای مقدمه هستم برای شروع تا کم کم برای پروژه های بیشتر در این تیم.

با این که میدونم احتمالا نسخه کتاب به صورت فایل پی دی اف یا صفحه وب قرار می دهید اما بنده میتونیم تا به اینجا فایل هایی که ارایه داده اید رو به صورت صفحات ژوپیتر نوت و تبدیل اون به صفحه وب مانند لینک های زیر هم قرار بدهم.

http://mkarimi21.me/DataMining_Tutorial/

or

http://mkarimi21.me/MCI_Project_Part01/FirstDemoIntro.html

**Comment by mthri** [comment]
سلام
بسیار عالی
میتونید ترجمه رو شروع کنید
لطفا یک زمان تقریبی برای اتمام ترجمتون مشخص کنید

برای موضوع ژوپیتر نوت یا صفحه وب، داخل گروه تلگرامی صحبت کنیم تا بچه هاهم نظرشون رو بگن

**Comment by MKarimi21** [comment]
در همین دی ماه انجام و ارسال می کنم

برای ژوپیتر و صفحه وب هم مطرح میکنم حتما
