### ISSUE TITLE
ترجمه فصل ۶

### ISSUE THREAD

**Issue by poyap** [ftg-iran/dfa-persian#24]

**Comment by poyap** [comment]
اگه فرصت زیاد داشته باشید، هردوش رو هم مشکلی ندارم.

**Comment by mthri** [comment]
سلام، فصل های یک و دو رزرو شده
فقط فصل های ۶ و ۷ باقی مونده

**Comment by poyap** [comment]
اوکی اگه میخواین ۶ با من

**Comment by mthri** [comment]
پس فصل ۶ برای شما
میتونید ترجمه رو شروع کنید
ممنون

**Comment by mthri** [comment]
یک زمان تقریبی از اتمام ترجمتون لطفا مشخص کنید

**Comment by poyap** [comment]
11/15‌ اوکیه؟

**Comment by mthri** [comment]
> 11/15‌ اوکیه؟

اره،‌ممنون
