### ISSUE TITLE
ترجمه فصل 7

### ISSUE THREAD

**Issue by Elo-No** [ftg-iran/dfa-persian#25]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mthri** [comment]
سلام، ممنون از شما 
میتونید ترجمه رو شروع کنید
فقط یک زمان حدودی از اتمامی ترجمه رو اعلام بفرمایید
