### ISSUE TITLE
ترجمه فصل 5

### ISSUE THREAD

**Issue by shahriargsp** [ftg-iran/dfa-persian#49]
من درخواست ترجمه فصل پنج را دارم.ترجمه را تا دوازدهم فروردین تحویل میدهم

**Comment by shahriargsp** [comment]
درصورتی که فصل 4 را کسی برعهده نگرفت من ترجمه آن را قبول میکنم

**Comment by BlackIQ** [comment]
سلام.

توی گروه میتونید مطرح کنید. ولی فکر کنم قبول کردن فصل جهار رو.

**Comment by BlackIQ** [comment]
سلام.

این فصل مترجم دارد.
