### ISSUE TITLE
Chapter 3

### ISSUE THREAD

**Issue by MrYazdan** [ftg-iran/dfa-persian#51]
Translation Chapter 3 
1/1/1401

**Comment by BlackIQ** [comment]
سلام. وقتتون بخیر.

توی گروه تلگرام هم میتونید مطرح کنید درخواست رو. ولی قکر کنم فصل سه مترجم داشته باشه.

**Comment by BlackIQ** [comment]
دوست عزیز چک کردم دیدم فصل 3 مترجم داره.

ایشون قبول کردند داخل این [این ایشو](https://github.com/ftg-iran/dfa-persian/issues/12).

**Comment by MrYazdan** [comment]
سلام ، چون دیدم قبول شده ولی انجام نشده خواستم جلو بیوفته.
موفق باشید.

**Comment by BlackIQ** [comment]
میتونید توی گروه باز مطرح کنید با ایشون همکاری کنید.
