### ISSUE TITLE
ترجمه فصل ۳

### ISSUE THREAD

**Issue by mitiebh** [ftg-iran/dfa-persian#56]
سلام. فصل سوم رو بنده ترجمه میکنم.
ددلاین نهایی 4 خرداد باشه مشکلی نیست؟ ممکنه زودتر هم done بشه ولی خب برای آخر هفته یه سری تسک های دیگه ای هم دارم.

**Comment by mthri** [comment]
سلام، اوکیه
تاریخ اتمام ۳/۴
